### ISSUE TITLE
機能詳細を考える

### ISSUE THREAD

**Issue by ENDOTAKUMI** [SymbaX/symbax#120]
## 2023/07/06相談
- [x] テーブル周りを整理したい
`events`テーブルで他に追加したり削除したい項目あれば
→ @daiwasan が今やってくれてるっぽい？
- [ ] アカウント削除時の動作
→ 【現状の動作】アカウントが削除されるとイベントが消える。
　→アカウントを消せないようにしたほうが良いか？ or 開催ステータスを新たに作成して中止ステータスなどに変更するか？
- [ ] イベント詳細ページ→参加者の一覧を現在出している
→イベント作成者のみ参加者のメアド公開とかしたほうが連絡先わかっていいかも？
- [ ] 他

**Comment by ENDOTAKUMI** [comment]
https://docs.google.com/spreadsheets/d/1TXnP2HUiykyBVWxzyyEG7aAiuoNuhPc2EhlEjGVmjXE/edit?usp=sharing

**Comment by daiwasan** [comment]
> ## 2023/07/06相談
> * [ ]  テーブル周りを整理したい
>   `events`テーブルで他に追加したり削除したい項目あれば
>   → @daiwasan が今やってくれてるっぽい？
> * [ ]  アカウント削除時の動作
>   → 【現状の動作】アカウントが削除されるとイベントが消える。
>   　→アカウントを消せないようにしたほうが良いか？ or 開催ステータスを新たに作成して中止ステータスなどに変更するか？
> * [ ]  イベント詳細ページ→参加者の一覧を現在出している
>   →イベント作成者のみ参加者のメアド公開とかしたほうが連絡先わかっていいかも？
> * [ ]  他

テーブル周り整理機能からやり始めたが昨日は寝まくってた。追加項目として募集期限のdeadlineってカラム追加した

アカウントの削除時の動作はステータスを新たに作成する方推し

イベント作成者のみ参加者の連絡先わかるの良いかも

**Comment by ENDOTAKUMI** [comment]
@daiwasan 

> アカウントの削除時の動作はステータスを新たに作成する方推し

テーブルの成約でusersから消えた時点で自動的に`events`、が消えるようになってるからテーブル周りだと
それ修正しないとかな。。
あとは参加予定のイベントはキャンセルでいいんかな？`event_participants`
（特に履歴は取ってないから最初から参加申込してないって扱いだけど。。）

**Comment by daiwasan** [comment]
@ENDOTAKUMI 
users が消えてもeventsが消えないようにすればいいのか

アカウント消したら参加予定のイベントどうなるかだよね、イベント中止されましたみたいな表示あった方がいいかもね

**Comment by ENDOTAKUMI** [comment]
編集機能作ったけど
参加者が5人いたとしても、
3人とか少ない数指定できるようになってるけどどうしよ

もし参加者がキャンセルした場合は再申し込み出来なくなってる
#148

**Comment by ENDOTAKUMI** [comment]
あといつでも編集できちゃうから過去のイベントとかは編集できないようにしたほうがいいかな...

**Comment by ENDOTAKUMI** [comment]
イベントのチェックイン機能とかあると便利かも（多分実装はめっちゃ大変だけど個人的に欲しい機能w)
https://zenn.dev/pocopota/articles/2d3d489272f724

**Comment by daiwasan** [comment]
> 編集機能作ったけど 参加者が5人いたとしても、 3人とか少ない数指定できるようになってるけどどうしよ
> 
> もし参加者がキャンセルした場合は再申し込み出来なくなってる #148

募集人数の枠を増やす、参加者を蹴る機能に合わせて参加した順番がわかるようにする？

**Comment by ENDOTAKUMI** [comment]
https://docs.google.com/document/d/1rcFg5mXU2FNboVLfZaii7EF-7-cwoyDL7xCoMNpATN8/edit?usp=drive_link
終了
