### ISSUE TITLE
[Feature]: 認証機能をカスタマイズする

### ISSUE THREAD

**Issue by ENDOTAKUMI** [SymbaX/symbax#14]
### 目的

認証機能をカスタマイズする
学科など必要な項目を登録できるようにする

### タスクリスト
- [x] 学科一覧テーブルを作る
- [x] registerページの項目を増やす
- [x] usersテーブルに項目を増やす
- [x] registerの処理に追加する
- [x] 学科の一覧をどっかから持ってきたい
- [x] 学校のメールアドレスでバリデーション

### 参考

#13 を完了してから。

**Comment by ENDOTAKUMI** [comment]
@MasayaSENGA 
@daiwasan 
@MACHIDAMinoru 
学科名のリストはDBに格納しといてそっから出力する？
それともプログラムの中に書いちゃうほうが楽？

**Comment by ENDOTAKUMI** [comment]
火曜日、環境がちゃんと動けばやりたいこと👆

**Comment by ENDOTAKUMI** [comment]
@MasayaSENGA 
@daiwasan 
@MACHIDAMinoru 
これ誰か作る？

**Comment by ENDOTAKUMI** [comment]
認証機能はlaravel breezeを使ってるからbreezeって言葉入れてググれば出てくるかも🤔

**Comment by ENDOTAKUMI** [comment]
@daiwasan 
マイグレーションファイル作れるー？

参考になりそう？なサイト：https://tech.amefure.com/php-laravel-migration

**Comment by daiwasan** [comment]
一応リンク見て進めてみてる、、、

**Comment by ENDOTAKUMI** [comment]
多分むずいから俺も明日見てみる。。。

**Comment by ENDOTAKUMI** [comment]
参考：セレクトボックス
https://takuma-it.com/laravel-prefecture-select-box/
https://www.searchlight8.com/laravel-mysql-viewdata/

**Comment by ENDOTAKUMI** [comment]
@daiwasan 
これどう？
メールアドレスのバリデーション

**Comment by ENDOTAKUMI** [comment]
```sh
git pull
git checkout -b fix/#14_email_validation
```
👆してから開発する

ここらへんのファイルいじればいけそう
app/Http/Controllers/Auth/RegisteredUserController.php

**Comment by ENDOTAKUMI** [comment]
@daiwasan 
バリデーションここらへんのコード

app/Http/Controllers/Auth/RegisteredUserController.php
```php
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:'.User::class],
            'password' => ['required', 'confirmed', Rules\Password::defaults()],
            'college' => ['required', 'exists:colleges,id'],
            'department' => ['required', 'exists:departments,id', Rule::exists('departments', 'id')->where(function ($query) use ($request) {
                $query->where('college_id', $request->input('college'));
            })],
        ]);
```

**Comment by ENDOTAKUMI** [comment]
@daiwasan 
参考になるかわからんけど
https://yutaro-blog.net/2021/05/04/laravel-validation-custom/

**Comment by ENDOTAKUMI** [comment]
@ENDOTAKUMI 
📝メモ
```sh
   'email' => [
                'required',
                'string',
                'email',
                'max:255',
                Rule::unique('users'),
                'regex:/^[^@]+@g\.neec\.ac\.jp$/',
            ],
```
