### ISSUE TITLE
[Feature]: プロフィールアイコン・自己紹介を設定できるようにする

### ISSUE THREAD

**Issue by ENDOTAKUMI** [SymbaX/symbax#177]
### 目的

プロフィールアイコン・自己紹介を設定できるようにする

### タスクリスト

- [x] DBにカラムを追加する
- [x] 登録欄を作成
- [x] 更新欄を作成
~~- [ ] 他人のプロフィールページみたいのもあれば~~
~~- [ ] 詳細ページの参加者名のよこに画像貼りたい~~ →別でタスク化しこのissueはclose #241

### 参考

https://qiita.com/Masahiro111/items/581f6e6b2d9eee4a9b8e
↑だと直接編集してるけど追記する方法で書いてほしい

**Comment by daiwasan** [comment]
メモ：新しくマイグレーションファイルつくる

**Comment by daiwasan** [comment]
**git pushできない対策メモ**

1. (https://qiita.com/mineaki27th/items/2fec99060f1c97ec2892)

1. chat GPT

エラーメッセージを見る限り、Gitの`push`操作中に通信の問題が発生しているようです。具体的には、リモートリポジトリとの通信中にタイムアウトが発生し、リモートサーバーが応答しなかったため、接続が切断されたようです。

この問題を解決するためには、以下のいくつかの手順を試すことができます。

1. インターネット接続を確認する: まず、インターネット接続が正常であることを確認してください。他のウェブサイトやオンラインサービスにアクセスできるか確認してください。

2. リモートリポジトリの状態を確認する: リモートリポジトリが正常に動作しているか確認してください。他のチームメンバーや共同作業者に問題があるかどうか確認してみてください。

3. 通信プロトコルを変更する: もしHTTP経由での通信を行っている場合、代わりにSSHプロトコルを使用してみてください。SSHを使用すると、通信の安定性が向上する場合があります。

4. `http.postBuffer`の設定を変更する: Gitが扱える最大のオブジェクトサイズを増やすために、`http.postBuffer`の設定を変更してみてください。以下のコマンドを実行して設定を変更できます。

   ```
   git config http.postBuffer 524288000
   ```

   上記の例では、バッファサイズを500 MBに設定しています。必要に応じて適切なサイズに調整してください。

これらの手順を試しても問題が解決しない場合は、問題がリモートリポジトリ側にある可能性があります。その場合は、リポジトリの管理者やホスティングサービスのサポートに連絡し、問題を報告することを検討してください。

**Comment by ENDOTAKUMI** [comment]
push出来ないの？

**Comment by daiwasan** [comment]
> push出来ないの？

うん明日確認する

**Comment by ENDOTAKUMI** [comment]
おけ、branchがmain, developだとpush出来ないけど
`git branch`で今いる確認しといて

**Comment by ENDOTAKUMI** [comment]
`database/migrations/2023_06_28_144920_create_event_participants_table.php`
user_idの紐づけの参考

**Comment by ENDOTAKUMI** [comment]
@daiwasan 
今日順調に進んだー？
