### ISSUE TITLE
[Feature]: イベント詳細ページのデザイン修正🖼

### ISSUE THREAD

**Issue by ENDOTAKUMI** [SymbaX/symbax#187]
### 目的

認証周りのデザインをいい感じにしてほしいです。
参加可能人数の表記消しちゃったから再度表示したい

### タスクリスト

- [ ] TBD…

**Comment by ENDOTAKUMI** [comment]
@daiwasan 
これはまだ作業中？

**Comment by daiwasan** [comment]
@ENDOTAKUMI 一か月くらいしかとしてすまない作業してない自己紹介終わったからこれやろうかな
