### ISSUE TITLE
[BUG]: Laravelの動作が遅い【解決しそう】

### ISSUE THREAD

**Issue by daiwasan** [SymbaX/symbax#19]
### 概要

ページを開くのに時間がかかる

### 再現手順

1.
2.
3.

### その他(other)

https://qiita.com/suzu6/items/8a8246015e5b45e210c4

**Comment by ENDOTAKUMI** [comment]
@daiwasan 
@MACHIDAMinoru 

## 動作を軽くする方法
予めMicrosoft StoreでUbuntuをインストールする。 （多分入ってる？）

Ubuntuで以下のディレクトリを作成する
`/home/[username]/project` ※[username]は環境によって変化

`project`ディレクトリの中で [環境構築](https://github.com/SymbaX/symbax/wiki/%E9%96%8B%E7%99%BA%E7%92%B0%E5%A2%83%E3%81%AE%E6%A7%8B%E7%AF%89-for-windows) を実行する
参考：https://www.rysys.jp/article/1356/

![sc](https://github.com/SymbaX/symbax/assets/33868170/dad82499-ce0e-4835-b518-2e6780efc3d4)

**Comment by ENDOTAKUMI** [comment]
DONE🎉
