### ISSUE TITLE
[Feature]: 画像を複数枚設定できるようにしたい

### ISSUE THREAD

**Issue by ENDOTAKUMI** [SymbaX/symbax#323]
### 目的

- 編集画面に画像を表示する
- 画像を追加、削除出来るようにする

表示はスライダー？

**Comment by ENDOTAKUMI** [comment]
https://pisuke-code.com/php-mysql-ways-to-store-array/

DBを修正して画像パスを配列で持っておくとか？

**Comment by ENDOTAKUMI** [comment]
📝メモ
https://qiita.com/sgrs38/items/7865142e649aa07e8582

**Comment by ENDOTAKUMI** [comment]
@MasayaSENGA 
そういえばこれどうなったー？

**Comment by MasayaSENGA** [comment]
@ENDOTAKUMI 
登録はできるようになった。
後は見た目頑張ってる。

**Comment by MasayaSENGA** [comment]
**めも**

画像テーブルを作る→既存のイベントが壊れちゃうどうしよう
画像が1〜4枚の時の処理→むずい思いつかん
画像サイズがバラバラな時→どうやって綺麗に揃えようか
