### ISSUE TITLE
かまた祭のスライドを作成

### ISSUE THREAD

**Issue by ENDOTAKUMI** [SymbaX/symbax#328]
### 目的

スライドを作成します

**Comment by ENDOTAKUMI** [comment]
🙋‍♂

**Comment by ENDOTAKUMI** [comment]
## 各サービス、ツールのロゴ
https://code.visualstudio.com/brand
https://aws.amazon.com/jp/architecture/icons/
https://github.com/laravel/art
https://github.com/logos
https://git-scm.com/downloads/logos
https://www.php.net/download-logos.php
https://www.docker.com/company/newsroom/media-resources/
https://www.cloudflare.com/ja-jp/logo/
https://discord.com/branding

**Comment by ENDOTAKUMI** [comment]
## [WIP]
[ここ](https://cm68rjzk-my.sharepoint.com/:p:/g/personal/admin_cm68rjzk_onmicrosoft_com/ETzk-8OUlrpCjunFZHAWyTYBqw3T6Plng3dUHRJHBHBFKQ?e=c8HzyN)で作業中

**Comment by ENDOTAKUMI** [comment]
発表時間って何分くらいあるっけ？

**Comment by ENDOTAKUMI** [comment]
![スクリーンショット 2023-09-19 10 35 30](https://github.com/SymbaX/symbax/assets/33868170/e6b26b2b-11f4-4cc8-9cfd-27283fd73778)

これ以外になんか使ってる？？
AWS分からん。

@MasayaSENGA

**Comment by MasayaSENGA** [comment]
@ENDOTAKUMI 
(あえて書くなら)Amazon VPCは使ってるかな

**Comment by ENDOTAKUMI** [comment]
おけ

**Comment by ENDOTAKUMI** [comment]
> ＊かまた祭の日程
> 
> 以下の日程でかまた祭のプレゼンを行います。
> 時間：11/4（土）、11/5（日）13:00～15:30（1チーム5分、担当の時間帯のみ来ればOK）
> 場所：720
> 聴講学生：2年生、3年生
> 
> プレゼン内容
> ・チーム紹介
> ・制作物と作ろうと思った経緯
> ・機能紹介
> ・設計書類あれば見せる
> ・動作しているところを見せる（動画。自動読み上げソフトは不可）
> ・使用環境（ハード、ソフト）
> ・今後の作業予定
> 
> 11/4か11/5どちらかになるかはこれから振り分けます。


https://classroom.google.com/c/NTE2OTU1NTQ2ODY3/p/NjMwMDkzNDIzMzE4/details

**Comment by ENDOTAKUMI** [comment]
#333
