### ISSUE TITLE
【優先】AWSにデプロイする

### ISSUE THREAD

**Issue by ENDOTAKUMI** [SymbaX/symbax#76]
### 目的

やり方わからないため一旦現在の環境でデプロイしてみたい

### タスクリスト

- [x] TBD…

**Comment by ENDOTAKUMI** [comment]
mainブランチにマージされたら自動でデプロイしたいな

**Comment by ENDOTAKUMI** [comment]
📝
https://note.com/ryoppei/n/nf2bf7ee78b0b

**Comment by MasayaSENGA** [comment]
5までできた

**Comment by ENDOTAKUMI** [comment]
5以降は難しいのー？
@MasayaSENGA

**Comment by MasayaSENGA** [comment]
アクセスキーが取得できないから無理かも

**Comment by ENDOTAKUMI** [comment]
@MasayaSENGA 
`AWS CodeCommitのSSHキー`がないんだっけ？
https://nttdocomo-developers.jp/entry/202212091200

**Comment by ENDOTAKUMI** [comment]
これは全然違うのか

**Comment by MasayaSENGA** [comment]
AWS_ACCESS_KEYとAWS_SECRET_ACCESS_KEYが欲しいけどIAMユーザ作成権限がないと無理っぽいたぶん

**Comment by ENDOTAKUMI** [comment]
言ったらもらえるのかなー
多分無理か、、笑
