### ISSUE TITLE
[拡張機能]: Prettierを導入する

### ISSUE THREAD

**Issue by ENDOTAKUMI** [SymbaX/symbax#87]
### 目的

**コード保存時に自動的にフォーマットする拡張機能です。**
導入してないと変なところで差分出そうだから全員導入する。

### タスクリスト

- [ ] Prettierを導入する
- [ ] 保存時に自動でフォーマットするように設定する

### 参考

https://ralacode.com/blog/post/vscode-prettier/

**Comment by daiwasan** [comment]
インストールした

**Comment by ENDOTAKUMI** [comment]
Done
